import { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import { BreadCrumbs } from '@/components/BreadCrumbs'
import { Footer } from '@/components/Footer'

import { getAbout } from '@/lib/api'
import markdownToHtml from '@/lib/markdownToHtml'

type Props = InferGetStaticPropsType<typeof getStaticProps>

/**
 * Aboutの内容を取得する
 */
export const getStaticProps = async () => {
  const about = getAbout(['title', 'content', 'updated'])

  // Markdown を HTML に変換する
  const content = await markdownToHtml(about.content)
  // content を詰め直して返す
  return {
    props: {
      about: {
        ...about,
        content,
      },
    },
  }
}

const About: NextPage<Props> = ({ about }) => {
  return (
    <div className='p-4 mx-auto md:p-6'>
      <Head>
        <title>{about.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>

      <main className='mx-auto max-w-3xl min-h-screen'>
        <BreadCrumbs
          lists={[
            {
              string: 'TeQu',
              path: '/',
            },
            {
              string: 'About',
              path: '/about',
            },
          ]}
        />
        <article className='my-10'>
          <div
            className='my-10 markdown'
            dangerouslySetInnerHTML={{ __html: about.content.replace(/href/g, "target='_blank' href") }}
          />
        </article>
      </main>
      <Footer />
    </div>
  )
}

export default About
