name: cron-deploy
on:
  schedule:
    # 09:00(JST) -> 0:00(UTC)
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
    steps:
      - name: Vercel Depoloy
        run: |
          curl --request POST \
          --url "$VERCEL_DEPLOY_HOOK_URL"
